server:
  port: 8888

spring:
  profiles:
    include: 'default'  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WajahatSiddiqui/RoomReservations.git
          baseDir: target/config
          searchPaths: configurations
        native:
          searchLocations: file:../config-local

