server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WajahatSiddiqui/RoomReservations
        baseDir: target/config
        searchPaths: configurations
        native:
          searchLocations: file:../config-local
